import { StyleSheet } from 'react-native';

export const offerStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  stateScreen: { flex: 1, backgroundColor: '#F9FAFB', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  stateText: { marginTop: 12, color: '#6B7280', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  stateButton: { marginTop: 18, backgroundColor: '#217A3C', borderRadius: 12, paddingHorizontal: 18, paddingVertical: 12 },
  stateButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 14, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  backBtn: { padding: 4, borderRadius: 8 },
  headerTitle: { fontSize: 16, fontWeight: '700', color: '#111827' },
  scrollContent: { padding: 14, paddingBottom: 20 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 14, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#111827', marginBottom: 4 },
  required: { color: '#EF4444' },
  optional: { fontSize: 11, color: '#9CA3AF', fontWeight: '400' },
  sectionSubtitle: { fontSize: 11, color: '#6B7280', marginBottom: 10 },
  input: { borderWidth: 1.5, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14, color: '#111827', backgroundColor: '#FAFAFA' },
  priceToggleRow: { flexDirection: 'row', gap: 8 },
  priceToggleBtn: { flex: 1, padding: 10, borderWidth: 2, borderColor: '#E5E7EB', borderRadius: 12, backgroundColor: 'transparent' },
  priceToggleBtnActive: { borderColor: '#2E9E52', backgroundColor: '#F2FBF5' },
  priceToggleLabel: { fontSize: 12, fontWeight: '700', color: '#374151' },
  priceToggleLabelActive: { color: '#1A6B34' },
  priceToggleSub: { fontSize: 11, color: '#9CA3AF', marginTop: 2 },
  priceToggleSubActive: { color: '#217A3C' },
  infoNote: { backgroundColor: '#F2FBF5', borderWidth: 1.5, borderColor: '#7FD4A0', borderRadius: 14, padding: 14, flexDirection: 'row', gap: 11, alignItems: 'flex-start' },
  infoNoteTitle: { fontSize: 13, fontWeight: '700', color: '#1A6B34', marginBottom: 4 },
  infoNoteText: { fontSize: 12, color: '#374151', lineHeight: 18 },
  errorBox: { marginTop: 12, backgroundColor: '#FEF3C7', borderWidth: 1, borderColor: '#FCD34D', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  errorText: { flex: 1, fontSize: 12, color: '#92400E', fontWeight: '700' },
  bottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#FFFFFF', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 28, borderTopWidth: 1, borderTopColor: '#F3F4F6', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 12, elevation: 8 },
});
