export const authTranslations = {
  en: {
    'auth.splashTagline': "Pakistan's Trusted Commodity Marketplace",
    'auth.poweredBy': 'Powered by Black Lion Technology',
    'auth.welcomeTagline':
      "Connect buyers and sellers across\nPakistan's agricultural commodity markets",
    'auth.verified': 'Verified',
    'auth.liveRates': 'Live Rates',
    'auth.secureDeals': 'Secure Deals',
    'auth.createAccount': 'Create Account',
    'auth.login': 'Log In',
    'auth.browseGuest': 'Browse as Guest',
    'auth.agreementStart': 'By continuing you agree to our',
    'auth.terms': 'Terms of Service',
    'auth.privacy': 'Privacy Policy',
    'auth.phoneStep': 'STEP 1 OF 2',
    'auth.otpStep': 'STEP 2 OF 2',
    'auth.phoneTitle': 'Enter Phone Number',
    'auth.phoneSubtitle': "We'll send you a verification code",
    'auth.mobileNumber': 'Mobile Number',
    'auth.phoneHelp': 'Enter your 10-11 digit mobile number',
    'auth.sendOtp': 'Send OTP →',
    'auth.otpTitle': 'Verify Number',
    'auth.codeSentTo': 'Code sent to',
    'auth.enterCode': 'Enter 6-Digit Code',
    'auth.didntReceive': "Didn't receive? ",
    'auth.resendCode': 'Resend Code',
    'auth.verifyContinue': 'Verify & Continue →',

    // Location
    'auth.locationStep': 'LOCATION',
    'auth.locationTitle': 'Your Location',
    'auth.locationSubtitle': 'We use this to show you relevant local market rates and buyers near you',
    'auth.locationInfo': 'Your location helps us connect you with the right buyers and show accurate commodity prices in your area.',
    'auth.locationSkip': 'Skip for Now',
    'auth.locationContinue': 'Continue →',
    'auth.selectedCity': 'Selected:',

    // Basic Info
    'auth.basicInfoStep': 'STEP 1 OF 5',
    'auth.basicInfoTitle': 'Personal Information',
    'auth.basicInfoSubtitle': 'Tell us about yourself to get started',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Muhammad Ali',
    'auth.email': 'Email Address',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Min. 8 characters',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Re-enter password',
    'auth.continueNext': 'Continue →',

    // Biz Info
    'auth.bizInfoStep': 'STEP 2 OF 5',
    'auth.bizInfoTitle': 'Business Information',
    'auth.bizInfoSubtitle': 'Help buyers and sellers know your business',
    'auth.businessName': 'Business / Farm Name',
    'auth.businessNamePlaceholder': 'Ali Traders',
    'auth.businessType': 'Business Type',
    'auth.selectBusinessType': 'Select Type...',
    'auth.businessTypeOptions': 'Farmer,Trader,Wholesaler,Retailer,Exporter',
    'auth.city': 'City / District',
    'auth.selectCity': 'Select City...',
    'auth.address': 'Full Address',
    'auth.addressPlaceholder': 'Street, Area, City',

    // ID Verify
    'auth.idVerifyStep': 'STEP 3 OF 5',
    'auth.idVerifyTitle': 'Identity Verification',
    'auth.idVerifySubtitle': 'Upload your CNIC to verify your identity',
    'auth.cnicNumber': 'CNIC Number',
    'auth.cnicPlaceholder': '35201-1234567-1',
    'auth.cnicFront': 'CNIC Front Side',
    'auth.cnicBack': 'CNIC Back Side',
    'auth.uploadPhoto': 'Tap to Upload Photo',
    'auth.idVerifyNote': 'Your ID is encrypted and only used for verification purposes.',

    // Payment Setup
    'auth.paymentStep': 'STEP 4 OF 5',
    'auth.paymentTitle': 'Payment\nSetup',
    'auth.paymentSubtitle': 'Add your bank account to receive payments',
    'auth.selectBank': 'Select Bank...',
    'auth.bankLabel': 'Bank Name',
    'auth.accountTitle': 'Account Title',
    'auth.accountTitlePlaceholder': 'Muhammad Ali',
    'auth.ibanNumber': 'IBAN / Account Number',
    'auth.ibanPlaceholder': 'PK36SCBL0000001123456702',
    'auth.walletLabel': 'Mobile Wallets (Optional)',
    'auth.submitRegistration': 'Submit Registration →',

    // Verify Pending
    'auth.verifyPendingTitle': 'Verification\nPending',
    'auth.verifyPendingSubtitle': 'Our team is reviewing your application. This usually takes 24-48 hours.',
    'auth.verifyPendingId': 'Identity Check',
    'auth.verifyPendingBiz': 'Business Verification',
    'auth.verifyPendingPayment': 'Payment Account',
    'auth.verifyPendingStatus': 'Pending Review',
    'auth.previewHome': 'Preview Home →',
    'auth.contactSupport': 'Contact Support',

    // Verify Approved
    'auth.verifyApprovedTitle': "You're Verified!",
    'auth.verifyApprovedSubtitle': 'Your account has been approved. You can now trade on the platform.',
    'auth.startTrading': 'Start Trading →',
  },
  ur: {
    'auth.splashTagline': 'پاکستان کی قابل اعتماد کموڈٹی مارکیٹ پلیس',
    'auth.poweredBy': 'بلیک لائن ٹیکنالوجی کی جانب سے',
    'auth.welcomeTagline':
      'پاکستان کی زرعی کموڈٹی مارکیٹس میں\nخریداروں اور فروخت کنندگان کو ملائیں',
    'auth.verified': 'تصدیق شدہ',
    'auth.liveRates': 'لائیو ریٹس',
    'auth.secureDeals': 'محفوظ ڈیلز',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    'auth.login': 'لاگ ان',
    'auth.browseGuest': 'مہمان کے طور پر دیکھیں',
    'auth.agreementStart': 'جاری رکھنے سے آپ ہماری',
    'auth.terms': 'شرائط خدمت',
    'auth.privacy': 'رازداری پالیسی',
    'auth.phoneStep': 'مرحلہ 1 از 2',
    'auth.otpStep': 'مرحلہ 2 از 2',
    'auth.phoneTitle': 'فون نمبر درج کریں',
    'auth.phoneSubtitle': 'ہم آپ کو تصدیقی کوڈ بھیجیں گے',
    'auth.mobileNumber': 'موبائل نمبر',
    'auth.phoneHelp': 'اپنا 10-11 ہندسوں کا موبائل نمبر درج کریں',
    'auth.sendOtp': 'OTP بھیجیں →',
    'auth.otpTitle': 'نمبر تصدیق کریں',
    'auth.codeSentTo': 'کوڈ بھیجا گیا',
    'auth.enterCode': '6 ہندسوں کا کوڈ درج کریں',
    'auth.didntReceive': 'موصول نہیں ہوا؟ ',
    'auth.resendCode': 'کوڈ دوبارہ بھیجیں',
    'auth.verifyContinue': 'تصدیق کریں اور جاری رکھیں →',

    'auth.locationStep': 'مقام',
    'auth.locationTitle': 'آپ کا مقام',
    'auth.locationSubtitle': 'ہم اسے مقامی مارکیٹ ریٹس اور قریبی خریداروں کو دکھانے کے لیے استعمال کرتے ہیں',
    'auth.locationInfo': 'آپ کا مقام ہمیں آپ کو صحیح خریداروں سے ملانے اور آپ کے علاقے میں درست اجناس کی قیمتیں دکھانے میں مدد کرتا ہے۔',
    'auth.locationSkip': 'ابھی چھوڑیں',
    'auth.locationContinue': 'جاری رکھیں →',
    'auth.selectedCity': 'منتخب:',

    'auth.basicInfoStep': 'مرحلہ 1 از 5',
    'auth.basicInfoTitle': 'ذاتی معلومات',
    'auth.basicInfoSubtitle': 'شروع کرنے کے لیے اپنے بارے میں بتائیں',
    'auth.fullName': 'پورا نام',
    'auth.fullNamePlaceholder': 'محمد علی',
    'auth.email': 'ای میل پتہ',
    'auth.emailPlaceholder': 'آپ کی@ای میل.com',
    'auth.password': 'پاس ورڈ',
    'auth.passwordPlaceholder': 'کم از کم 8 حروف',
    'auth.confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'auth.confirmPasswordPlaceholder': 'پاس ورڈ دوبارہ درج کریں',
    'auth.continueNext': 'جاری رکھیں →',

    'auth.bizInfoStep': 'مرحلہ 2 از 5',
    'auth.bizInfoTitle': 'کاروباری معلومات',
    'auth.bizInfoSubtitle': 'خریداروں اور فروخت کنندگان کو اپنا کاروبار بتائیں',
    'auth.businessName': 'کاروبار / فارم کا نام',
    'auth.businessNamePlaceholder': 'علی ٹریڈرز',
    'auth.businessType': 'کاروبار کی قسم',
    'auth.selectBusinessType': 'قسم منتخب کریں...',
    'auth.businessTypeOptions': 'کسان,تاجر,تھوک فروش,خوردہ فروش,برآمد کنندہ',
    'auth.city': 'شہر / ضلع',
    'auth.selectCity': 'شہر منتخب کریں...',
    'auth.address': 'مکمل پتہ',
    'auth.addressPlaceholder': 'گلی، علاقہ، شہر',

    'auth.idVerifyStep': 'مرحلہ 3 از 5',
    'auth.idVerifyTitle': 'شناخت کی تصدیق',
    'auth.idVerifySubtitle': 'اپنی شناخت کی تصدیق کے لیے شناختی کارڈ اپ لوڈ کریں',
    'auth.cnicNumber': 'شناختی کارڈ نمبر',
    'auth.cnicPlaceholder': '35201-1234567-1',
    'auth.cnicFront': 'شناختی کارڈ کا سامنے',
    'auth.cnicBack': 'شناختی کارڈ کا پیچھے',
    'auth.uploadPhoto': 'تصویر اپ لوڈ کرنے کے لیے ٹیپ کریں',
    'auth.idVerifyNote': 'آپ کی شناخت خفیہ ہے اور صرف تصدیق کے لیے استعمال ہوتی ہے۔',

    'auth.paymentStep': 'مرحلہ 4 از 5',
    'auth.paymentTitle': 'ادائیگی\nسیٹ اپ',
    'auth.paymentSubtitle': 'ادائیگیاں وصول کرنے کے لیے اپنا بینک اکاؤنٹ شامل کریں',
    'auth.selectBank': 'بینک منتخب کریں...',
    'auth.bankLabel': 'بینک کا نام',
    'auth.accountTitle': 'اکاؤنٹ کا نام',
    'auth.accountTitlePlaceholder': 'محمد علی',
    'auth.ibanNumber': 'IBAN / اکاؤنٹ نمبر',
    'auth.ibanPlaceholder': 'PK36SCBL0000001123456702',
    'auth.walletLabel': 'موبائل والٹس (اختیاری)',
    'auth.submitRegistration': 'رجسٹریشن جمع کریں →',

    'auth.verifyPendingTitle': 'تصدیق\nجاری ہے',
    'auth.verifyPendingSubtitle': 'ہماری ٹیم آپ کی درخواست کا جائزہ لے رہی ہے۔ یہ عام طور پر 24-48 گھنٹے لیتا ہے۔',
    'auth.verifyPendingId': 'شناخت کی جانچ',
    'auth.verifyPendingBiz': 'کاروباری تصدیق',
    'auth.verifyPendingPayment': 'ادائیگی اکاؤنٹ',
    'auth.verifyPendingStatus': 'جائزہ زیرِ التوا',
    'auth.previewHome': 'ہوم دیکھیں →',
    'auth.contactSupport': 'سپورٹ سے رابطہ کریں',

    'auth.verifyApprovedTitle': 'آپ کی تصدیق ہو گئی!',
    'auth.verifyApprovedSubtitle': 'آپ کا اکاؤنٹ منظور ہو گیا ہے۔ اب آپ پلیٹ فارم پر تجارت کر سکتے ہیں۔',
    'auth.startTrading': 'تجارت شروع کریں →',
  },
} as const;
