export const authTranslations = {
  en: {
    'auth.splashTagline': "Pakistan's Trusted Commodity Marketplace",
    'auth.welcomeTagline':
      "Connect buyers and sellers across\nPakistan's agricultural commodity markets",
    'auth.verified': 'Verified',
    'auth.liveRates': 'Live Rates',
    'auth.secureDeals': 'Secure Deals',
    'auth.createAccount': 'Create Account',
    'auth.login': 'Log In',
    'auth.browseGuest': 'Browse as Guest',
    'auth.agreementStart': 'By continuing you agree to our',
    'auth.terms': 'Terms of Service',
    'auth.privacy': 'Privacy Policy',
    'auth.phoneStep': 'STEP 1 OF 2',
    'auth.otpStep': 'STEP 2 OF 2',
    'auth.phoneTitle': 'Enter Your\nPhone Number',
    'auth.phoneSubtitle': "We'll send you a verification code",
    'auth.mobileNumber': 'Mobile Number',
    'auth.phoneHelp': 'Enter your 10-11 digit mobile number',
    'auth.sendOtp': 'Send OTP →',
    'auth.otpTitle': 'Verify Your\nNumber',
    'auth.codeSentTo': 'Code sent to',
    'auth.enterCode': 'Enter 6-Digit Code',
    'auth.didntReceive': "Didn't receive? ",
    'auth.resendCode': 'Resend Code',
    'auth.verifyContinue': 'Verify & Continue →',
  },
  ur: {
    'auth.splashTagline': 'پاکستان کی قابل اعتماد کموڈٹی مارکیٹ پلیس',
    'auth.welcomeTagline':
      'پاکستان کی زرعی کموڈٹی مارکیٹس میں\nخریداروں اور فروخت کنندگان کو ملائیں',
    'auth.verified': 'تصدیق شدہ',
    'auth.liveRates': 'لائیو ریٹس',
    'auth.secureDeals': 'محفوظ ڈیلز',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    'auth.login': 'لاگ ان',
    'auth.browseGuest': 'مہمان کے طور پر دیکھیں',
    'auth.agreementStart': 'جاری رکھنے سے آپ ہماری',
    'auth.terms': 'شرائط خدمت',
    'auth.privacy': 'رازداری پالیسی',
    'auth.phoneStep': 'مرحلہ 1 از 2',
    'auth.otpStep': 'مرحلہ 2 از 2',
    'auth.phoneTitle': 'اپنا\nفون نمبر درج کریں',
    'auth.phoneSubtitle': 'ہم آپ کو تصدیقی کوڈ بھیجیں گے',
    'auth.mobileNumber': 'موبائل نمبر',
    'auth.phoneHelp': 'اپنا 10-11 ہندسوں کا موبائل نمبر درج کریں',
    'auth.sendOtp': 'OTP بھیجیں →',
    'auth.otpTitle': 'اپنا\nنمبر تصدیق کریں',
    'auth.codeSentTo': 'کوڈ بھیجا گیا',
    'auth.enterCode': '6 ہندسوں کا کوڈ درج کریں',
    'auth.didntReceive': 'موصول نہیں ہوا؟ ',
    'auth.resendCode': 'کوڈ دوبارہ بھیجیں',
    'auth.verifyContinue': 'تصدیق کریں اور جاری رکھیں →',
  },
} as const;
