export const commonTranslations = {
  en: {
    'tabs.home': 'Home',
    'tabs.market': 'Market',
    'tabs.deals': 'Deals',
    'tabs.post': 'Post',
    'tabs.profile': 'Profile',

    'common.approved': 'Approved',
    'common.pending': 'Pending',
    'common.primary': 'Primary',
    'common.saved': 'Saved',
    'common.saveChanges': 'Save Changes',
    'common.updateProfile': 'Update Profile',
    'common.profileUpdated': 'Profile Updated',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.on': 'On',
    'common.off': 'Off',
    'common.versionValue': 'v2.4.1',
    'common.cacheValue': '12 MB',
    'common.currencyValue': 'PKR ₨',
    'common.browseMarketplace': 'Browse Marketplace',
    'common.verifiedDate': 'Verified {{date}}',
    'common.verifiedDash': 'Verified —',
    'common.loading': 'Loading...',
    'common.updating': 'Updating...',
    'common.rejected': 'Rejected',
  },
  ur: {
    'tabs.home': 'ہوم',
    'tabs.market': 'مارکیٹ',
    'tabs.deals': 'ڈیلز',
    'tabs.post': 'پوسٹ',
    'tabs.profile': 'پروفائل',

    'common.approved': 'منظور شدہ',
    'common.pending': 'زیر التواء',
    'common.primary': 'بنیادی',
    'common.saved': 'محفوظ',
    'common.saveChanges': 'تبدیلیاں محفوظ کریں',
    'common.updateProfile': 'پروفائل اپ ڈیٹ کریں',
    'common.profileUpdated': 'پروفائل اپ ڈیٹ ہو گیا',
    'common.enabled': 'فعال',
    'common.disabled': 'غیر فعال',
    'common.on': 'آن',
    'common.off': 'آف',
    'common.versionValue': 'v2.4.1',
    'common.cacheValue': '12 MB',
    'common.currencyValue': 'PKR ₨',
    'common.browseMarketplace': 'مارکیٹ پلیس دیکھیں',
    'common.verifiedDate': '{{date}} کو تصدیق شدہ',
    'common.verifiedDash': 'تصدیق شدہ —',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.updating': 'اپ ڈیٹ ہو رہا ہے...',
    'common.rejected': 'مسترد',
  },
} as const;
