export const commonTranslations = {
  en: {
    'tabs.home': 'Home',
    'tabs.market': 'Market',
    'tabs.deals': 'Deals',
    'tabs.post': 'Post',
    'tabs.profile': 'Profile',

    'common.approved': 'Approved',
    'common.pending': 'Pending',
    'common.primary': 'Primary',
    'common.saved': 'Saved',
    'common.saveChanges': 'Save Changes',
    'common.updateProfile': 'Update Profile',
    'common.profileUpdated': 'Profile Updated',
    'common.enabled': 'Enabled',
    'common.on': 'On',
    'common.versionValue': 'v2.4.1',
    'common.cacheValue': '12 MB',
    'common.currencyValue': 'PKR ₨',
    'common.browseMarketplace': 'Browse Marketplace',
    'common.verifiedDate': 'Verified {{date}}',
    'common.verifiedDash': 'Verified —',
  },
  ur: {
    'tabs.home': 'ہوم',
    'tabs.market': 'مارکیٹ',
    'tabs.deals': 'ڈیلز',
    'tabs.post': 'پوسٹ',
    'tabs.profile': 'پروفائل',

    'common.approved': 'منظور شدہ',
    'common.pending': 'زیر التواء',
    'common.primary': 'بنیادی',
    'common.saved': 'محفوظ',
    'common.saveChanges': 'تبدیلیاں محفوظ کریں',
    'common.updateProfile': 'پروفائل اپ ڈیٹ کریں',
    'common.profileUpdated': 'پروفائل اپ ڈیٹ ہو گیا',
    'common.enabled': 'فعال',
    'common.on': 'آن',
    'common.versionValue': 'v2.4.1',
    'common.cacheValue': '12 MB',
    'common.currencyValue': 'PKR ₨',
    'common.browseMarketplace': 'مارکیٹ پلیس دیکھیں',
    'common.verifiedDate': '{{date}} کو تصدیق شدہ',
    'common.verifiedDash': 'تصدیق شدہ —',
  },
} as const;
