export const dealsTranslations = {
  en: {
    'deals.myDeals': 'My Deals',
    'deals.myOrders': 'My Orders',
    'deals.totalDeals': '{{count}} total deals',
    'deals.active': 'Active',
    'deals.payment': 'Payment',
    'deals.transit': 'Transit',
    'deals.completed': 'Completed',
    'deals.inTransit': 'In Transit',
    'deals.all': 'All',
    'deals.stage': 'Stage {{stage}}/12',
    'deals.complete': '{{pct}}% complete',
    'deals.noDeals': 'No deals found',
    'deals.differentFilter': 'Try a different filter',

    'deal.quantity': 'Quantity',
    'deal.rate': 'Rate',
    'deal.location': 'Location',
    'deal.buyer': 'Buyer',
    'deal.seller': 'Seller',
    'deal.progress': 'Deal Progress',
    'deal.paymentSchedule': 'Payment Schedule',
    'deal.actions': 'Actions',
    'deal.negotiate': '💬 Negotiate',
    'deal.dispute': '📋 Dispute',
    'deal.paid': 'Paid',
    'deal.pending': 'Pending',
  },
  ur: {
    'deals.myDeals': 'میری ڈیلز',
    'deals.myOrders': 'میرے آرڈرز',
    'deals.totalDeals': '{{count}} کل ڈیلز',
    'deals.active': 'فعال',
    'deals.payment': 'ادائیگی',
    'deals.transit': 'ٹرانزٹ',
    'deals.completed': 'مکمل',
    'deals.inTransit': 'راستے میں',
    'deals.all': 'سب',
    'deals.stage': 'مرحلہ {{stage}}/12',
    'deals.complete': '{{pct}}% مکمل',
    'deals.noDeals': 'کوئی ڈیل نہیں ملی',
    'deals.differentFilter': 'دوسرا فلٹر آزمائیں',

    'deal.quantity': 'مقدار',
    'deal.rate': 'ریٹ',
    'deal.location': 'مقام',
    'deal.buyer': 'خریدار',
    'deal.seller': 'سیلر',
    'deal.progress': 'ڈیل پیش رفت',
    'deal.paymentSchedule': 'ادائیگی شیڈول',
    'deal.actions': 'اقدامات',
    'deal.negotiate': '💬 بات چیت',
    'deal.dispute': '📋 تنازعہ',
    'deal.paid': 'ادا شدہ',
    'deal.pending': 'زیر التواء',
  },
} as const;
