export const marketplaceTranslations = {
  en: {
    'home.buyer': 'Buyer',
    'home.seller': 'Seller',
    'home.buyerMode': 'Buyer Mode',
    'home.sellerMode': 'Seller Mode',
    'home.location': 'Lahore, Punjab',
    'home.activeDeals': 'Active Deals',
    'home.demands': 'Demands',
    'home.totalSpent': 'Total Spent',
    'home.supplies': 'Supplies',
    'home.orders': 'Orders',
    'home.earnings': 'Earnings',
    'home.marketRates': 'Market Rates',
    'home.seeAll': 'See All',
    'home.featuredSupplies': 'Featured Supplies',
    'home.viewAll': 'View All',
    'home.browseCategories': 'Browse Categories',
    'home.all': 'All',
    'home.totalEarningsMonth': 'Total Earnings (This Month)',
    'home.released': 'Released',
    'home.pending': 'Pending',
    'home.thisWeek': 'This Week',
    'home.quickActions': 'Quick Actions',
    'home.createSupply': 'Create Supply',
    'home.createSupplySub': 'List your stock',
    'home.myListings': 'My Listings',
    'home.myListingsSub': 'Manage stock',
    'home.viewOrders': 'View Orders',
    'home.viewOrdersSub': 'Track deals',
    'home.payouts': 'Payouts',
    'home.payoutsSub': 'Earnings',

    'market.buyCommodities': 'Buy Commodities',
    'market.buyerDemands': 'Buyer Demands',
    'market.listingsAvailable': '{{count}} listings available',
    'market.activeRequests': '{{count}} active requests',
    'market.filter': 'Filter',
    'market.searchCommodities': 'Search commodities, locations...',
    'market.searchRequests': 'Search buyer requests...',
    'market.by': 'by',
    'market.interest': 'Interest',
    'market.active': 'Active',
    'market.pending': 'Pending',
    'market.submitOffer': 'Submit Offer',
    'market.noResults': 'No results found',
    'market.adjustSearch': 'Try adjusting your search or filters',

    'post.demandPosted': 'Demand Posted!',
    'post.listingCreated': 'Listing Created!',
    'post.sellerNotify': 'Sellers will be notified and can submit offers.',
    'post.listingReview':
      "Your listing is under review. You'll be notified once approved.",
    'post.postAnother': 'Post Another',
    'post.postDemandTitle': '📋 Post a Demand',
    'post.createListingTitle': '📦 Create Listing',
    'post.postDemandSub': 'Let sellers know what you need',
    'post.createListingSub': 'List your commodity for buyers',
    'post.commodity': 'Commodity',
    'post.quantityUnit': 'Quantity & Unit',
    'post.budget': 'Budget (per 40kg)',
    'post.askingPrice': 'Asking Price (per 40kg)',
    'post.location': 'Location',
    'post.notes': 'Additional Notes',
    'post.buyerNotesPlaceholder': 'Quality grade, delivery preference...',
    'post.sellerNotesPlaceholder': 'Quality, packaging, availability...',
    'post.postDemand': '📋 Post Demand',
    'post.submitListing': '📦 Submit Listing',

    'listing.verified': 'Verified',
    'listing.deals': 'deals',
    'listing.available': '{{qty}} available',
    'listing.location': 'Location',
    'listing.seller': 'Seller',
    'listing.quantity': 'Quantity',
    'listing.price': 'Price',
    'listing.about': 'About this Listing',
    'listing.priceBreakdown': 'Price Breakdown',
    'listing.unitPrice': 'Unit Price',
    'listing.commission': 'Commission',
    'listing.estDelivery': 'Est. Delivery',
    'listing.totalPer': 'Total (per 40kg)',
    'listing.chat': '💬 Chat',
    'listing.sendInterest': 'Send Interest',
    'listing.sendOffer': 'Send Offer',
  },
  ur: {
    'home.buyer': 'خریدار',
    'home.seller': 'سیلر',
    'home.buyerMode': 'خریدار موڈ',
    'home.sellerMode': 'سیلر موڈ',
    'home.location': 'لاہور، پنجاب',
    'home.activeDeals': 'فعال ڈیلز',
    'home.demands': 'ڈیمانڈز',
    'home.totalSpent': 'کل خرچ',
    'home.supplies': 'سپلائیز',
    'home.orders': 'آرڈرز',
    'home.earnings': 'آمدنی',
    'home.marketRates': 'مارکیٹ ریٹس',
    'home.seeAll': 'سب دیکھیں',
    'home.featuredSupplies': 'نمایاں سپلائیز',
    'home.viewAll': 'سب دیکھیں',
    'home.browseCategories': 'کیٹیگریز دیکھیں',
    'home.all': 'سب',
    'home.totalEarningsMonth': 'کل آمدنی (اس ماہ)',
    'home.released': 'جاری شدہ',
    'home.pending': 'زیر التواء',
    'home.thisWeek': 'اس ہفتے',
    'home.quickActions': 'فوری اقدامات',
    'home.createSupply': 'سپلائی بنائیں',
    'home.createSupplySub': 'اپنا اسٹاک لسٹ کریں',
    'home.myListings': 'میری لسٹنگز',
    'home.myListingsSub': 'اسٹاک منظم کریں',
    'home.viewOrders': 'آرڈرز دیکھیں',
    'home.viewOrdersSub': 'ڈیلز ٹریک کریں',
    'home.payouts': 'ادائیگیاں',
    'home.payoutsSub': 'آمدنی',

    'market.buyCommodities': 'کموڈٹیز خریدیں',
    'market.buyerDemands': 'خریدار ڈیمانڈز',
    'market.listingsAvailable': '{{count}} لسٹنگز دستیاب',
    'market.activeRequests': '{{count}} فعال درخواستیں',
    'market.filter': 'فلٹر',
    'market.searchCommodities': 'کموڈٹیز، مقامات تلاش کریں...',
    'market.searchRequests': 'خریدار درخواستیں تلاش کریں...',
    'market.by': 'از',
    'market.interest': 'دلچسپی',
    'market.active': 'فعال',
    'market.pending': 'زیر التواء',
    'market.submitOffer': 'آفر جمع کریں',
    'market.noResults': 'کوئی نتیجہ نہیں ملا',
    'market.adjustSearch': 'اپنی تلاش یا فلٹرز تبدیل کریں',

    'post.demandPosted': 'ڈیمانڈ پوسٹ ہو گئی!',
    'post.listingCreated': 'لسٹنگ بن گئی!',
    'post.sellerNotify':
      'سیلرز کو اطلاع دی جائے گی اور وہ آفرز جمع کر سکیں گے۔',
    'post.listingReview':
      'آپ کی لسٹنگ جائزے میں ہے۔ منظوری کے بعد آپ کو اطلاع دی جائے گی۔',
    'post.postAnother': 'دوسری پوسٹ کریں',
    'post.postDemandTitle': '📋 ڈیمانڈ پوسٹ کریں',
    'post.createListingTitle': '📦 لسٹنگ بنائیں',
    'post.postDemandSub': 'سیلرز کو بتائیں آپ کو کیا چاہیے',
    'post.createListingSub': 'اپنی کموڈٹی خریداروں کے لیے لسٹ کریں',
    'post.commodity': 'کموڈٹی',
    'post.quantityUnit': 'مقدار اور یونٹ',
    'post.budget': 'بجٹ (فی 40kg)',
    'post.askingPrice': 'طلب قیمت (فی 40kg)',
    'post.location': 'مقام',
    'post.notes': 'اضافی نوٹس',
    'post.buyerNotesPlaceholder': 'کوالٹی گریڈ، ڈیلیوری ترجیح...',
    'post.sellerNotesPlaceholder': 'کوالٹی، پیکنگ، دستیابی...',
    'post.postDemand': '📋 ڈیمانڈ پوسٹ کریں',
    'post.submitListing': '📦 لسٹنگ جمع کریں',

    'listing.verified': 'تصدیق شدہ',
    'listing.deals': 'ڈیلز',
    'listing.available': '{{qty}} دستیاب',
    'listing.location': 'مقام',
    'listing.seller': 'سیلر',
    'listing.quantity': 'مقدار',
    'listing.price': 'قیمت',
    'listing.about': 'اس لسٹنگ کے بارے میں',
    'listing.priceBreakdown': 'قیمت کی تفصیل',
    'listing.unitPrice': 'یونٹ قیمت',
    'listing.commission': 'کمیشن',
    'listing.estDelivery': 'متوقع ڈیلیوری',
    'listing.totalPer': 'کل (فی 40kg)',
    'listing.chat': '💬 چیٹ',
    'listing.sendInterest': 'دلچسپی بھیجیں',
    'listing.sendOffer': 'آفر بھیجیں',
  },
} as const;
