export const profileTranslations = {
  en: {
    'profile.approved': 'Approved',
    'profile.deals': 'Deals',
    'profile.supplies': 'Supplies',
    'profile.rating': 'Rating',
    'profile.account': 'ACCOUNT',
    'profile.preferences': 'PREFERENCES',
    'profile.support': 'SUPPORT',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfoSub': 'Name, email, phone',
    'profile.businessProfile': 'Business Profile',
    'profile.businessProfileSub': 'Company, type, location',
    'profile.paymentMethods': 'Payment Methods',
    'profile.paymentMethodsSub': 'Bank account, wallets',
    'profile.verificationStatus': 'Verification Status',
    'profile.verificationStatusSub': 'KYC approved',
    'profile.savedListings': 'Saved Listings',
    'profile.savedListingsSub': 'Your favorites',
    'profile.notifications': 'Notifications',
    'profile.notificationsSub': 'Manage alerts',
    'profile.appSettings': 'App Settings',
    'profile.appSettingsSub': 'Language, theme',
    'profile.helpSupport': 'Contact Support',
    'profile.helpSupportSub': '+92 300 NASEEB',
    'profile.termsPrivacy': 'Terms & Privacy',
    'profile.termsPrivacySub': 'Legal documents',
    'profile.payments': 'PAYMENTS',
    'profile.paymentHistory': 'Payment History',
    'profile.paymentHistorySub': 'All transactions & receipts',
    'profile.logout': 'Log Out',
    'profile.disputes': 'Disputes & Queries',
    'profile.disputesSub': 'Tickets & support queries',

    'personal.title': 'Personal Information',
    'personal.changePhoto': 'Change Photo',
    'personal.fullName': 'Full Name',
    'personal.email': 'Email',
    'personal.phone': 'Phone',
    'personal.city': 'City',
    'personal.dateOfBirth': 'Date of Birth',
    'personal.cnic': 'CNIC',
    'personal.placeholderFullName': 'Enter full name',
    'personal.placeholderEmail': 'Enter email',
    'personal.placeholderPhone': 'Enter phone',
    'personal.placeholderCity': 'Enter city',
    'personal.placeholderDateOfBirth': 'Enter date of birth',
    'personal.placeholderCnic': 'XXXXX-XXXXXXX-X',

    'business.title': 'Business Profile',
    'business.verifiedSellerSince': 'Verified Seller · Since 2021',
    'business.verifiedSeller': 'Verified Seller',
    'business.businessName': 'Business Name',
    'business.businessType': 'Business Type',
    'business.registrationNo': 'Registration No',
    'business.primaryCrop': 'Primary Crop',
    'business.farmLocation': 'Farm Location',
    'business.farmSize': 'Farm Size',
    'business.placeholderBusinessName': 'Business name',
    'business.placeholderBusinessType': 'Business type',
    'business.placeholderRegistrationNo': 'Registration number',
    'business.placeholderPrimaryCrop': 'Primary crop',
    'business.placeholderFarmLocation': 'Farm location',
    'business.placeholderFarmSize': 'Farm size',

    'payments.title': 'Payment Methods',
    'payments.linkedBankAccount': 'LINKED BANK ACCOUNT',
    'payments.hblBankAccount': 'HBL Bank Account',
    'payments.maskedAccount': '•••• •••• 4821',
    'payments.noBankAccounts': 'No linked bank accounts yet',
    'payments.bankName': 'Bank Name',
    'payments.accountName': 'Account Name',
    'payments.accountTitle': 'Account Title',
    'payments.accountNo': 'Account No',
    'payments.iban': 'IBAN',
    'payments.mobileWallet': 'MOBILE WALLET',
    'payments.easypaisa': 'Easypaisa',
    'payments.addNewAccount': 'Add New Account',
    'payments.saveAccount': 'Save Account',
    'payments.updateAccount': 'Update Account',
    'payments.cancel': 'Cancel',
    'payments.edit': 'Edit',
    'payments.delete': 'Delete',

    'verification.title': 'Verification Status',
    'verification.accountVerified': 'Account Verified',
    'verification.accountVerifiedSub':
      'Your account is fully verified and active',
    'verification.accountPending': 'Verification Pending',
    'verification.accountPendingSub':
      'Your account verification is still in progress',
    'verification.cnic': 'CNIC Verification',
    'verification.businessDocs': 'Business Docs',
    'verification.bankAccount': 'Bank Account',
    'verification.phone': 'Phone Verification',
    'verification.address': 'Address Verification',
    'verification.feb10': 'Feb 10, 2024',
    'verification.feb12': 'Feb 12, 2024',
    'verification.feb14': 'Feb 14, 2024',

    'saved.title': 'Saved Listings',
    'saved.count': '{{count}} saved items',
    'saved.emptyTitle': 'No saved listings',
    'saved.emptyBody':
      'Tap the heart icon on any listing to save it here for quick access.',

    'appSettings.title': 'App Settings',
    'appSettings.display': 'DISPLAY',
    'appSettings.security': 'SECURITY',
    'appSettings.data': 'DATA',
    'appSettings.language': 'Language',
    'appSettings.currency': 'Currency',
    'appSettings.changePin': 'Change PIN',
    'appSettings.biometricLogin': 'Biometric Login',
    'appSettings.twoFactorAuth': 'Two-Factor Auth',
    'appSettings.clearCache': 'Clear Cache',
    'appSettings.appVersion': 'App Version',
    'appSettings.selectCurrency': 'Select Currency',
    'appSettings.pkr': 'Pakistani Rupee (PKR)',
    'appSettings.usd': 'US Dollar (USD)',
    'appSettings.cancel': 'Cancel',

    'notifications.title': 'Notifications',
    'notifications.newDealAlerts': 'New Deal Alerts',
    'notifications.newDealAlertsSub': 'When a deal is created for you',
    'notifications.offerUpdates': 'Offer Updates',
    'notifications.offerUpdatesSub': 'Status changes on your offers',
    'notifications.paymentAlerts': 'Payment Alerts',
    'notifications.paymentAlertsSub': 'Payment confirmed or pending',
    'notifications.dispatchDelivery': 'Dispatch & Delivery',
    'notifications.dispatchDeliverySub': 'Shipment tracking updates',
    'notifications.promotions': 'Promotions',
    'notifications.promotionsSub': 'Naseeb news and feature updates',
    'notifications.sms': 'SMS Notifications',
    'notifications.smsSub': 'Receive alerts via SMS',

    'support.title': 'Help & Support',
    'support.subtitle': "We're here to help",
    'support.contactUs': 'Contact Us',
    'support.faq': 'Frequently Asked Questions',
    'support.whatsapp': 'WhatsApp',
    'support.email': 'Email',
    'support.helpline': 'Helpline',
    'support.qPostDemand': 'How do I post a demand?',
    'support.aPostDemand':
      'Go to the Post tab, select your commodity, enter quantity, price and location, then tap "Post Demand".',
    'support.qPayments': 'How are payments handled?',
    'support.aPayments':
      'Payments are staged: 30% advance, 40% on dispatch, and 30% on delivery. Naseeb holds funds in escrow until both parties confirm.',
    'support.qKyc': 'How long does KYC take?',
    'support.aKyc':
      'KYC verification typically takes 1-2 business days after submitting all required documents.',
    'support.qCancelDeal': 'Can I cancel a deal?',
    'support.aCancelDeal':
      'Deals can be cancelled before the "Deal Agreed" stage. After that, cancellation is subject to review and may incur a penalty.',
    'support.qTrackShipment': 'How do I track my shipment?',
    'support.aTrackShipment':
      'Go to your deal in the Deals tab and tap "Track Shipment" once the deal reaches the In Transit stage.',

    'terms.title': 'Terms & Privacy',
    'terms.subtitle': 'Last updated January 2024',
    'terms.legalDocuments': 'Legal Documents',
    'terms.bannerBody':
      'Please read these terms carefully before using Naseeb Agri Market.',
    'terms.agree': 'I Agree to Terms',
    'terms.acceptanceTitle': '1. Acceptance of Terms',
    'terms.acceptanceBody':
      'By creating an account and using Naseeb Agri Market, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the platform.',
    'terms.accountsTitle': '2. User Accounts',
    'terms.accountsBody':
      'You must be at least 18 years of age and provide accurate information during registration. You are responsible for maintaining the confidentiality of your account credentials.',
    'terms.listingsTitle': '3. Commodity Listings',
    'terms.listingsBody':
      'All listings must represent actual, available stock. Fraudulent or misleading listings will result in immediate account suspension. Naseeb reserves the right to remove any listing without notice.',
    'terms.paymentTitle': '4. Payment & Escrow',
    'terms.paymentBody':
      'All payments are processed through our escrow system. Funds are held securely and released only upon confirmed delivery and inspection. Naseeb charges a 1% commission on completed deals.',
    'terms.disputeTitle': '5. Dispute Resolution',
    'terms.disputeBody':
      'Disputes must be raised within 48 hours of delivery. Our resolution team will mediate and may request supporting evidence. Decisions by Naseeb in dispute cases are final.',
    'terms.privacyTitle': '6. Privacy Policy',
    'terms.privacyBody':
      'We collect personal and business information to facilitate trading. We do not sell your data to third parties. Data is used solely for platform operations, fraud prevention, and service improvement.',
    'terms.liabilityTitle': '7. Limitation of Liability',
    'terms.liabilityBody':
      'Naseeb is a marketplace facilitator and is not liable for the quality, quantity, or delivery of commodities. Traders transact at their own risk after accepting these terms.',
  },
  ur: {
    'profile.approved': 'منظور شدہ',
    'profile.deals': 'ڈیلز',
    'profile.supplies': 'سپلائیز',
    'profile.rating': 'ریٹنگ',
    'profile.account': 'اکاؤنٹ',
    'profile.preferences': 'ترجیحات',
    'profile.support': 'سپورٹ',
    'profile.personalInfo': 'ذاتی معلومات',
    'profile.personalInfoSub': 'نام، ای میل، فون',
    'profile.businessProfile': 'کاروباری پروفائل',
    'profile.businessProfileSub': 'کمپنی، قسم، مقام',
    'profile.paymentMethods': 'ادائیگی کے طریقے',
    'profile.paymentMethodsSub': 'بینک اکاؤنٹ، والٹس',
    'profile.verificationStatus': 'تصدیقی حیثیت',
    'profile.verificationStatusSub': 'KYC منظور شدہ',
    'profile.savedListings': 'محفوظ لسٹنگز',
    'profile.savedListingsSub': 'آپ کی پسندیدہ اشیاء',
    'profile.notifications': 'اطلاعات',
    'profile.notificationsSub': 'الرٹس منظم کریں',
    'profile.appSettings': 'ایپ سیٹنگز',
    'profile.appSettingsSub': 'زبان، تھیم',
    'profile.helpSupport': 'رابطہ سپورٹ',
    'profile.helpSupportSub': '+92 300 NASEEB',
    'profile.termsPrivacy': 'شرائط اور رازداری',
    'profile.termsPrivacySub': 'قانونی دستاویزات',
    'profile.payments': 'ادائیگیاں',
    'profile.paymentHistory': 'ادائیگی کی تاریخ',
    'profile.paymentHistorySub': 'تمام لین دین اور رسیدیں',
    'profile.logout': 'لاگ آؤٹ',
    'profile.disputes': 'تنازعات اور سوالات',
    'profile.disputesSub': 'ٹکٹس اور سپورٹ سوالات',

    'personal.title': 'ذاتی معلومات',
    'personal.changePhoto': 'تصویر تبدیل کریں',
    'personal.fullName': 'پورا نام',
    'personal.email': 'ای میل',
    'personal.phone': 'فون',
    'personal.city': 'شہر',
    'personal.dateOfBirth': 'تاریخ پیدائش',
    'personal.cnic': 'شناختی کارڈ',
    'personal.placeholderFullName': 'پورا نام درج کریں',
    'personal.placeholderEmail': 'ای میل درج کریں',
    'personal.placeholderPhone': 'فون درج کریں',
    'personal.placeholderCity': 'شہر درج کریں',
    'personal.placeholderDateOfBirth': 'تاریخ پیدائش درج کریں',
    'personal.placeholderCnic': 'XXXXX-XXXXXXX-X',

    'business.title': 'کاروباری پروفائل',
    'business.verifiedSellerSince': 'تصدیق شدہ سیلر · 2021 سے',
    'business.verifiedSeller': 'تصدیق شدہ سیلر',
    'business.businessName': 'کاروبار کا نام',
    'business.businessType': 'کاروبار کی قسم',
    'business.registrationNo': 'رجسٹریشن نمبر',
    'business.primaryCrop': 'اہم فصل',
    'business.farmLocation': 'فارم کا مقام',
    'business.farmSize': 'فارم کا سائز',
    'business.placeholderBusinessName': 'کاروبار کا نام',
    'business.placeholderBusinessType': 'کاروبار کی قسم',
    'business.placeholderRegistrationNo': 'رجسٹریشن نمبر',
    'business.placeholderPrimaryCrop': 'اہم فصل',
    'business.placeholderFarmLocation': 'فارم کا مقام',
    'business.placeholderFarmSize': 'فارم کا سائز',

    'payments.title': 'ادائیگی کے طریقے',
    'payments.linkedBankAccount': 'منسلک بینک اکاؤنٹ',
    'payments.hblBankAccount': 'HBL بینک اکاؤنٹ',
    'payments.maskedAccount': '•••• •••• 4821',
    'payments.noBankAccounts': 'ابھی کوئی بینک اکاؤنٹ منسلک نہیں',
    'payments.bankName': 'بینک کا نام',
    'payments.accountName': 'اکاؤنٹ نام',
    'payments.accountTitle': 'اکاؤنٹ ٹائٹل',
    'payments.accountNo': 'اکاؤنٹ نمبر',
    'payments.iban': 'IBAN',
    'payments.mobileWallet': 'موبائل والٹ',
    'payments.easypaisa': 'ایزی پیسہ',
    'payments.addNewAccount': 'نیا اکاؤنٹ شامل کریں',
    'payments.saveAccount': 'اکاؤنٹ محفوظ کریں',
    'payments.updateAccount': 'اکاؤنٹ اپ ڈیٹ کریں',
    'payments.cancel': 'منسوخ کریں',
    'payments.edit': 'ترمیم',
    'payments.delete': 'حذف کریں',

    'verification.title': 'تصدیقی حیثیت',
    'verification.accountVerified': 'اکاؤنٹ تصدیق شدہ',
    'verification.accountVerifiedSub':
      'آپ کا اکاؤنٹ مکمل طور پر تصدیق شدہ اور فعال ہے',
    'verification.accountPending': 'تصدیق زیر التواء',
    'verification.accountPendingSub': 'آپ کے اکاؤنٹ کی تصدیق جاری ہے',
    'verification.cnic': 'شناختی کارڈ کی تصدیق',
    'verification.businessDocs': 'کاروباری دستاویزات',
    'verification.bankAccount': 'بینک اکاؤنٹ',
    'verification.phone': 'فون تصدیق',
    'verification.address': 'پتے کی تصدیق',
    'verification.feb10': '10 فروری، 2024',
    'verification.feb12': '12 فروری، 2024',
    'verification.feb14': '14 فروری، 2024',

    'saved.title': 'محفوظ لسٹنگز',
    'saved.count': '{{count}} محفوظ اشیاء',
    'saved.emptyTitle': 'کوئی محفوظ لسٹنگ نہیں',
    'saved.emptyBody':
      'کسی بھی لسٹنگ پر دل کا آئیکن دبا کر اسے فوری رسائی کے لیے یہاں محفوظ کریں۔',

    'appSettings.title': 'ایپ سیٹنگز',
    'appSettings.display': 'ڈسپلے',
    'appSettings.security': 'سیکیورٹی',
    'appSettings.data': 'ڈیٹا',
    'appSettings.language': 'زبان',
    'appSettings.currency': 'کرنسی',
    'appSettings.changePin': 'پن تبدیل کریں',
    'appSettings.biometricLogin': 'بائیومیٹرک لاگ ان',
    'appSettings.twoFactorAuth': 'دو مرحلہ تصدیق',
    'appSettings.clearCache': 'کیش صاف کریں',
    'appSettings.appVersion': 'ایپ ورژن',
    'appSettings.selectCurrency': 'کرنسی منتخب کریں',
    'appSettings.pkr': 'پاکستانی روپیہ (PKR)',
    'appSettings.usd': 'امریکی ڈالر (USD)',
    'appSettings.cancel': 'منسوخ کریں',

    'notifications.title': 'اطلاعات',
    'notifications.newDealAlerts': 'نئی ڈیل الرٹس',
    'notifications.newDealAlertsSub': 'جب آپ کے لیے ڈیل بنائی جائے',
    'notifications.offerUpdates': 'آفر اپ ڈیٹس',
    'notifications.offerUpdatesSub': 'آپ کی آفرز کی حیثیت میں تبدیلی',
    'notifications.paymentAlerts': 'ادائیگی الرٹس',
    'notifications.paymentAlertsSub': 'ادائیگی مکمل یا زیر التواء',
    'notifications.dispatchDelivery': 'ڈسپیچ اور ڈیلیوری',
    'notifications.dispatchDeliverySub': 'شپمنٹ ٹریکنگ اپ ڈیٹس',
    'notifications.promotions': 'پروموشنز',
    'notifications.promotionsSub': 'نصیب کی خبریں اور فیچر اپ ڈیٹس',
    'notifications.sms': 'SMS اطلاعات',
    'notifications.smsSub': 'SMS کے ذریعے الرٹس وصول کریں',

    'support.title': 'مدد اور سپورٹ',
    'support.subtitle': 'ہم مدد کے لیے موجود ہیں',
    'support.contactUs': 'ہم سے رابطہ کریں',
    'support.faq': 'اکثر پوچھے گئے سوالات',
    'support.whatsapp': 'واٹس ایپ',
    'support.email': 'ای میل',
    'support.helpline': 'ہیلپ لائن',
    'support.qPostDemand': 'میں ڈیمانڈ کیسے پوسٹ کروں؟',
    'support.aPostDemand':
      'پوسٹ ٹیب پر جائیں، اپنی کموڈٹی منتخب کریں، مقدار، قیمت اور مقام درج کریں، پھر "Post Demand" دبائیں۔',
    'support.qPayments': 'ادائیگیاں کیسے ہینڈل ہوتی ہیں؟',
    'support.aPayments':
      'ادائیگیاں مراحل میں ہوتی ہیں: 30% ایڈوانس، 40% ڈسپیچ پر، اور 30% ڈیلیوری پر۔ نصیب دونوں فریقوں کی تصدیق تک رقم ایسکرو میں رکھتا ہے۔',
    'support.qKyc': 'KYC میں کتنا وقت لگتا ہے؟',
    'support.aKyc':
      'تمام مطلوبہ دستاویزات جمع کرانے کے بعد KYC تصدیق عموماً 1-2 کاروباری دن لیتی ہے۔',
    'support.qCancelDeal': 'کیا میں ڈیل منسوخ کر سکتا ہوں؟',
    'support.aCancelDeal':
      'ڈیل "Deal Agreed" مرحلے سے پہلے منسوخ کی جا سکتی ہے۔ اس کے بعد منسوخی جائزے سے مشروط ہے اور جرمانہ ہو سکتا ہے۔',
    'support.qTrackShipment': 'میں اپنی شپمنٹ کیسے ٹریک کروں؟',
    'support.aTrackShipment':
      'Deals ٹیب میں اپنی ڈیل کھولیں اور جب ڈیل In Transit مرحلے پر پہنچے تو "Track Shipment" دبائیں۔',

    'terms.title': 'شرائط اور رازداری',
    'terms.subtitle': 'آخری اپ ڈیٹ جنوری 2024',
    'terms.legalDocuments': 'قانونی دستاویزات',
    'terms.bannerBody':
      'نصیب ایگری مارکیٹ استعمال کرنے سے پہلے براہ کرم یہ شرائط غور سے پڑھیں۔',
    'terms.agree': 'میں شرائط سے متفق ہوں',
    'terms.acceptanceTitle': '1. شرائط کی قبولیت',
    'terms.acceptanceBody':
      'اکاؤنٹ بنا کر اور نصیب ایگری مارکیٹ استعمال کر کے آپ ان شرائط خدمت اور ہماری رازداری پالیسی کے پابند ہونے سے اتفاق کرتے ہیں۔ اگر آپ اتفاق نہیں کرتے تو پلیٹ فارم استعمال نہ کریں۔',
    'terms.accountsTitle': '2. صارف اکاؤنٹس',
    'terms.accountsBody':
      'آپ کی عمر کم از کم 18 سال ہونی چاہیے اور رجسٹریشن کے دوران درست معلومات فراہم کرنی ہوں گی۔ آپ اپنے اکاؤنٹ کی اسناد کی رازداری برقرار رکھنے کے ذمہ دار ہیں۔',
    'terms.listingsTitle': '3. کموڈٹی لسٹنگز',
    'terms.listingsBody':
      'تمام لسٹنگز حقیقی اور دستیاب اسٹاک کی نمائندگی کریں۔ دھوکہ دہی یا گمراہ کن لسٹنگز پر اکاؤنٹ فوری معطل ہو سکتا ہے۔ نصیب کسی بھی لسٹنگ کو نوٹس کے بغیر ہٹانے کا حق رکھتا ہے۔',
    'terms.paymentTitle': '4. ادائیگی اور ایسکرو',
    'terms.paymentBody':
      'تمام ادائیگیاں ہمارے ایسکرو سسٹم کے ذریعے پراسیس ہوتی ہیں۔ رقم محفوظ رکھی جاتی ہے اور تصدیق شدہ ڈیلیوری اور معائنہ کے بعد جاری کی جاتی ہے۔ مکمل ڈیلز پر نصیب 1% کمیشن لیتا ہے۔',
    'terms.disputeTitle': '5. تنازعہ حل',
    'terms.disputeBody':
      'تنازعہ ڈیلیوری کے 48 گھنٹوں کے اندر اٹھایا جانا چاہیے۔ ہماری ٹیم ثالثی کرے گی اور ثبوت طلب کر سکتی ہے۔ تنازعہ کیسز میں نصیب کا فیصلہ حتمی ہو گا۔',
    'terms.privacyTitle': '6. رازداری پالیسی',
    'terms.privacyBody':
      'ہم ٹریڈنگ کے لیے ذاتی اور کاروباری معلومات جمع کرتے ہیں۔ ہم آپ کا ڈیٹا تیسرے فریق کو فروخت نہیں کرتے۔ ڈیٹا صرف پلیٹ فارم آپریشنز، فراڈ روک تھام اور سروس بہتری کے لیے استعمال ہوتا ہے۔',
    'terms.liabilityTitle': '7. ذمہ داری کی حد',
    'terms.liabilityBody':
      'نصیب ایک مارکیٹ پلیس سہولت کار ہے اور کموڈٹیز کے معیار، مقدار یا ڈیلیوری کا ذمہ دار نہیں۔ تاجر ان شرائط کو قبول کرنے کے بعد اپنے رسک پر لین دین کرتے ہیں۔',
  },
} as const;
